# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-19 16:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('branch_code', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.TextField(blank=True, max_length=25)),
                ('user_type', models.CharField(blank=True, choices=[('client', 'client'), ('supplier', 'supplier'), ('affiliate', 'affiliate')], default='client', max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('town', models.CharField(blank=True, max_length=30)),
                ('banking_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zim.BankingDetails')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
