# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-20 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import zim.models


class Migration(migrations.Migration):

    dependencies = [
        ('zim', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=zim.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zim.Product'),
        ),
    ]
