# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-23 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zim', '0006_order_orderitem_orderitemattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='session',
        ),
    ]
